export const getbookings = 'user/bookings'
export const getNotifications = 'user/notifications'
export const updateUser = 'user/update/details'
export const sentOtpChangeEmail = 'user/change_email'
export const ChangeEmail = 'user/confirm_change_email'
export const sentOtpChangePassword = 'user/change_password_otp'
export const changePassword = 'user/confirm_change_password'
export const checkUsername = 'user/check_username'
export const changeUserProfile = 'user/change_user_profile'
export const saveFCMtoken = 'user/save_fcmtoken'

// player games 
export const GetAllGames = 'game/get_games'
export const GetUsersGame = 'game/get_user_games'
export const CreateGame = 'game/create'
export const filterGames = 'game/filter'
export const getGameDetails = 'game/game_details'
export const requestGame = 'game/request'
export const CheckUserInGame = 'game/check_user_game'
export const CheckUserJoinedGames = 'game/check_user_all_game'
export const getUserHostedGame = 'game/get_user_hosted_games'
export const getUserJoinedGame = 'game/get_user_joined_games'
export const getGameRequests = 'game/get_game_requests'
export const acceptGameRequest = 'game/accept_request'
export const rejectGameRequest = 'game/reject_request'
export const getGameChats = 'game/game_chats'
